# Assessing coefficients with bootstrapping

[Machine Learning Interpretability course](https://www.trainindata.com/p/machine-learning-interpretability)

In this notebook, we will use bootstrapping to determine the error of the coefficients.

if the coefficients are significant, then the contribution of the feature towards the probability is meaningful.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy import stats

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

### Load data

To obtain the data, check the folder `prepare-data` in this repo, or section 2 of the course.

In [2]:
# load titanic dataset

df = pd.read_csv('../titanic.csv')

# split data
X_train, X_test, y_train, y_test = train_test_split(
    df.drop("survived", axis=1), 
    df["survived"],
    test_size=0.15,
    random_state=1,
)

# scale the variables
scaler = StandardScaler().set_output(transform="pandas")

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

## Bootstrapping with Scikit-learn

In the linear regression section, we used cross-validation and different partitions of the train set to estimate the error of the coefficients. Those are valid approaches and you can use them for logistic regression as well.

Here, I will introduce another alternative to estimate the coefficients error: **bootstrapping**.

In [3]:
# Train 50 models on different bootstrapped
# partitions of the train set

s = dict()

for i in np.linspace(1, 50, num=50):

    # bootstrap with replacement
    X_train_b = X_train.sample(frac=0.8, replace=True, random_state=int(i))
    y_train_b = y_train.loc[X_train_b.index]

    # train model
    logit = LogisticRegression(
        l1_ratio=0, random_state=0).fit(X_train_b, y_train_b)

    # store coefficients
    s[str(int(i))] = pd.Series(logit.coef_[0])

In [4]:
# put coefficients in a dataframe

df = pd.concat(s, axis=1)
df.index = logit.feature_names_in_

df.head()

,1,2,3,4,5,6,7,8,9,10,...,41,42,43,44,45,46,47,48,49,50
pclass,-0.514840,-0.611006,-0.348623,-0.426293,-0.501894,-0.431216,-0.563103,-0.461773,-0.604161,-0.523517,...,-0.428241,-0.372520,-0.608070,-0.405712,-0.452622,-0.507103,-0.387917,-0.394691,-0.577614,-0.382687
sibsp,-0.065397,-0.171984,-0.322308,-0.076778,-0.083549,-0.398051,-0.175544,-0.081418,-0.203474,-0.320109,...,-0.169011,-0.240783,-0.293037,-0.392560,-0.329479,-0.340095,-0.138665,-0.390749,-0.182415,-0.282350
parch,0.017933,0.074278,0.065390,-0.030263,-0.003641,0.034640,0.178391,0.005448,-0.141736,0.051318,...,0.099019,0.299594,0.027176,0.138650,0.055425,-0.000217,0.074984,0.099311,0.101684,0.051322
sex_female,1.035554,1.200001,1.206013,1.194330,1.156431,1.287638,1.181939,1.273751,1.173238,1.229270,...,1.154634,1.072136,1.170112,1.280273,1.235855,1.317010,1.162197,1.090320,1.347751,1.128617
embarked_S,0.069252,0.128076,0.129597,0.161813,-0.018737,0.187903,-0.067115,0.032689,0.038137,-0.027196,...,0.005535,-0.133080,0.170183,-0.047680,0.135503,0.066179,-0.091696,-0.083338,0.010494,-0.038741

In [5]:
# Summarize variability of coefficients

coeff_summary = df.agg(["mean", "std"], axis=1)

coeff_summary

                mean       std
pclass     -0.502038  0.113885
sibsp      -0.236148  0.099211
parch       0.060879  0.095763
sex_female  1.204159  0.090267
embarked_S  0.007766  0.124982
embarked_C  0.247924  0.122380
cabin_B    -0.180538  0.136748
cabin_C    -0.315041  0.142717
cabin_E     0.017523  0.132985
cabin_D    -0.155720  0.132862
cabin_A    -0.025743  0.161083
cabin_M    -0.595927  0.207983
cabin_G    -0.153173  0.174190

In [6]:
# calculate z and the p-values

coeff_summary["z"] = coeff_summary["mean"] / coeff_summary["std"]

coeff_summary["p_values"] = stats.norm.sf(abs(coeff_summary["z"]))*2  # two sided

coeff_summary

                mean       std          z      p_values
pclass     -0.502038  0.113885  -4.408300  1.041850e-05
sibsp      -0.236148  0.099211  -2.380261  1.730039e-02
parch       0.060879  0.095763   0.635722  5.249579e-01
sex_female  1.204159  0.090267  13.340002  1.354567e-40
embarked_S  0.007766  0.124982   0.062135  9.504557e-01
embarked_C  0.247924  0.122380   2.025856  4.277951e-02
cabin_B    -0.180538  0.136748  -1.320231  1.867579e-01
cabin_C    -0.315041  0.142717  -2.207460  2.728196e-02
cabin_E     0.017523  0.132985   0.131770  8.951661e-01
cabin_D    -0.155720  0.132862  -1.172042  2.411803e-01
cabin_A    -0.025743  0.161083  -0.159812  8.730295e-01
cabin_M    -0.595927  0.207983  -2.865270  4.166545e-03
cabin_G    -0.153173  0.174190  -0.879347  3.792131e-01

Experimentally, we have larger errors, and therefore, the significance is smaller. 

This is probably because the variables are not completely independent, that is, there is some colinearity.